# File: .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv venv
          echo ". .venv/bin/activate" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]"

      - name: Run mypy
        run: mypy .

      - name: Run bandit
        run: bandit -r .
